WebApp/Controllers/DocumentoTiposController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Domain.Entities;
using Microsoft.Extensions.Logging;
using Application.Interfaces.Services;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Controllers
{
    public partial class DocumentoTiposController : Controller
    {

        private readonly ILogger<DocumentosController> _logger;
        private readonly IDocumentoTipoService _documentoTipoService;

        public DocumentoTiposController(ILogger<DocumentosController> logger,
                                        IDocumentoTipoService documentoTipoService)
        {
            try
            {
                _logger = logger;
                _documentoTipoService = documentoTipoService;
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.Message);
                throw ex;
            }
        }

        public async Task<IActionResult> Index()
        {
            return View(await _documentoTipoService.GetAllAsync());
        }

        // GET: DocumentoTipos/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var documento = await _documentoTipoService.GetByIdAsync(id);
            if (documento == null)
            {
                return NotFound();
            }

            return View(documento);
        }

        // GET: DocumentoTipos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DocumentoTipos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DocumentoTipo documentoTipo)
        {
            if (ModelState.IsValid)
            {
                var result = await _documentoTipoService.AddAsync(documentoTipo);
                return RedirectToAction(nameof(Index));
            }

            return View(documentoTipo);
        }

        // GET: DocumentoTipos/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var documentoTipo = await _documentoTipoService.GetByIdAsync(id);
            if (documentoTipo == null)
            {
                return NotFound();
            }
            return View(documentoTipo);
        }

        // POST: DocumentoTipos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, DocumentoTipo documentoTipo)
        {
            if (id != documentoTipo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _documentoTipoService.UpdateAsync(id, documentoTipo);

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            return View(documentoTipo);
        }

        // GET: DocumentoTipos/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var cliente = await _documentoTipoService.GetByIdAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: DocumentoTipos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _documentoTipoService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public JsonResult GetAllRecords()
        {
            var data = _documentoTipoService.GetAllAsync().Result;

            //List<Documento> documents = new List<Documento>();
            //foreach (var document in data)
            //{
            //    documents.Add(new Document { Id = document.Id, Description = document.Description, PersonId = document.PersonId, DocumentTypeId = document.DocumentTypeId });
            //}

            var output = new { status = "success", total = data.Count(), records = data };

            return Json(output);
        }


    }
}

WebApp/Controllers/DocumentosController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Domain.Entities;
using Microsoft.Extensions.Logging;
using Application.Interfaces.Services;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Controllers
{
    public partial class DocumentosController : Controller
    {

        private readonly ILogger<DocumentosController> _logger;
        private readonly IDocumentoService _documentoService;
        private readonly IDocumentoTipoService _documentoTipoService;
        private readonly IPersonaService _personaService;

        public DocumentosController(ILogger<DocumentosController> logger,
                                    IDocumentoService documentoService,
                                    IDocumentoTipoService documentoTipoService,
                                    IPersonaService personaService)
        {
            try
            {
                _logger = logger;
                _documentoService = documentoService;
                _documentoTipoService = documentoTipoService;
                _personaService = personaService;
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.Message);
                throw ex;
            }
        }

        public IActionResult Index()
        {
            return View(_documentoService.GetAllAsync());
        }

        // GET: Documentos/Details/5
        public IActionResult Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var documento = _documentoService.GetByIdAsync(id);
            if (documento == null)
            {
                return NotFound();
            }

            return View(documento);
        }

        // GET: Documentos/Create
        public async Task<IActionResult> CreateAsync()
        {
            ViewData["DocumentoTipoId"] = new SelectList(await _documentoTipoService.GetAllAsync(), "Id", "Descripcion");
            ViewData["PersonaId"] = new SelectList(await _personaService.GetAllAsync(), "Id", "NombreCompleto");
            return View();
        }

        // POST: Documentos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Documento documento)
        {
            if (ModelState.IsValid)
            {
                var result = await _documentoService.AddAsync(documento);
                return RedirectToAction(nameof(Index));
            }

            ViewData["DocumentoTipoId"] = new SelectList(await _documentoTipoService.GetAllAsync(), "Id", "Descripcion", documento.DocumentoTipoId);
            ViewData["PersonaId"] = new SelectList(await _personaService.GetAllAsync(), "Id", "NombreCompleto", documento.PersonaId);
            return View(documento);
        }

        // GET: Documentos/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var documento = _documentoService.GetByIdAsync(id).Result;
            if (documento == null)
            {
                return NotFound();
            }
            ViewData["DocumentoTipoId"] = new SelectList(await _documentoTipoService.GetAllAsync(), "Id", "Descripcion", documento.DocumentoTipoId);
            ViewData["PersonaId"] = new SelectList(await _personaService.GetAllAsync(), "Id", "NombreCompleto", documento.PersonaId);
            return View(documento);
        }

        // POST: Documentos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Documento documento)
        {
            if (id != documento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _documentoService.UpdateAsync(id, documento);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            ViewData["DocumentoTipoId"] = new SelectList(await _documentoTipoService.GetAllAsync(), "Id", "Descripcion", documento.DocumentoTipoId);
            ViewData["PersonaId"] = new SelectList(await _personaService.GetAllAsync(), "Id", "NombreCompleto", documento.PersonaId);
            return View(documento);
        }

        // GET: Documentos/Delete/5
        public async Task<IActionResult>  Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var cliente = await _documentoService.GetByIdAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Documentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _documentoService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public JsonResult GetAllRecords()
        {
            var data = _documentoService.GetAllAsync().Result;
            var output = new { status = "success", total = data.Count(), records = data };

            return Json(output);
        }
    }
}

WebApp/Controllers/PersonasController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Domain.Entities;
using Microsoft.Extensions.Logging;
using Application.Interfaces.Services;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace WebApp.Controllers
{
    public partial class PersonasController : Controller
    {

        private readonly ILogger<PersonasController> _logger;
        private readonly IPersonaService _personaService;

        public PersonasController(ILogger<PersonasController> logger,
                                  IPersonaService personaService)
        {
            try
            {
                _logger = logger;
                _personaService = personaService;
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.Message);
                throw ex;
            }
        }

        public async Task<IActionResult> Index()
        {
            return View( await _personaService.GetAllAsync());
        }

        // GET: Personas/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var persona = await _personaService.GetByIdAsync(id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // GET: Personas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Persona persona)
        {
            if (ModelState.IsValid)
            {
                var result = await _personaService.AddAsync(persona);
                return RedirectToAction(nameof(Index));
            }

            return View(persona);
        }

        // GET: Personas/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var persona = await _personaService.GetByIdAsync(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Persona persona)
        {
            if (id != persona.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _personaService.UpdateAsync(id, persona);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            return View(persona);
        }

        // GET: Personas/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var cliente = await _personaService.GetByIdAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _personaService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(string request)
        {
            dynamic response = JsonConvert.DeserializeObject(request);

            Persona input = response.ToObject<Persona>();

            try
            {
                if (input.Id != 0)
                {
                    var result = await _personaService.UpdateAsync(input.Id, input);
                    return Json(new { status = "success" });
                }

                else
                {
                    var person = new Persona
                    {
                        Nombre = input.Nombre,
                        Apellido = input.Apellido,
                        FechaNacimiento = input.FechaNacimiento
                    };
                    var result = await _personaService.AddAsync(input);
                    return Json(new { status = "success" });
                }
            }
            catch
            {
                return Json(new { status = "error", message = "La operación no ha podido realizarse debido a un error en el servidor." });
            }
        }

        //[HttpPost]
        //public async Task<IActionResult> Delete(int id)
        //{
        //    try
        //    {
        //        var result = await _personaService.RemoveAsync(id);
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new { status = "error", message = $"Ha ocurrido un error al realizar la operación. {ex}" });
        //    }
        //}


        [HttpGet]
        public JsonResult GetAllRecords()
        {
            var data = _personaService.GetAllAsync().Result;
            var output = new { status = "success", total = data.Count(), records = data };
            return Json(output);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin Panel</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/dist/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/dist/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/dist/Ionicons/css/ionicons.min.css">

    <link rel="stylesheet" href="~/dist/flag-icon-css/css/flag-icon.min.css" />

    @RenderSection("Styles", required: false)

    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/admin-lte/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/dist/admin-lte/css/skins/_all-skins.min.css">

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">



    <script src="~/dist/jquery/jquery.min.js"></script>
    <script src="~/dist/w2ui/w2ui.min.js"></script>
    <link href="~/dist/w2ui/w2ui.min.css" rel="stylesheet" />

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>PE</b>F</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Genica</b></span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    @*<partial name="_LoginPartial" />*@
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>Shehryar Khan</p>
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form (Optional) -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- Sidebar Menu -->
                @Html.Partial("_MainMenu")
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong>Copyright &copy; 2020 <a href="#">Genica</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery -->
    @*<script src="~/dist/jquery/jquery.min.js"></script>*@





    <!-- Bootstrap 3.3.7 -->
    <script src="~/dist/bootstrap/js/bootstrap.min.js"></script>

    @RenderSection("Scripts", required: false)

    <!-- SlimScroll -->
    <script src="~/dist/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/dist/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/admin-lte/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/admin-lte/js/demo.js"></script>
</body>
</html>

WebApp/Views/Shared/_MainMenu.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">HEADER</li>
    <!-- Optionally, you can add icons to the links -->

    <li class="nav-item @(Html.IsMenuActive("/") ? "active" : "")">
        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index"><i class="fa fa-link"></i> Home</a>
    </li>

    <li class="nav-item @(Html.IsMenuActive("/Home/Privacy") ? "active" : "")">
        <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy"><i class="fa fa-link"></i> Privacy</a>
    </li>

    <li class="nav-item @(Html.IsMenuActive("/Home/Contact") ? "active" : "")">
        <a class="nav-link text-dark" asp-controller="Home" asp-action="Contact"><i class="fa fa-link"></i> Contact</a>
    </li>

    <li class="nav-item @(Html.IsMenuActive("/Home/About") ? "active" : "")">
        <a class="nav-link text-dark" asp-controller="Home" asp-action="About"><i class="fa fa-link"></i> About</a>
    </li>

    <li class="treeview @(Html.IsMenuActive("/Contactos") ? "active" : "")">
        <a href="/Contactos">
            <i class="fa fa-users"></i> <span>Relaciones</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>

        <ul class="treeview-menu">
            <li class="nav-item @(Html.IsMenuActive("/Documentos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Documentos" asp-action="Index"><i class="fa fa-user"></i> Documentos</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/DocumentoTipos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="DocumentoTipos" asp-action="Index"><i class="fa fa-user"></i> Documento Tipos</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/Personas") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Personas" asp-action="Index"><i class="fa fa-user"></i> Personas</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/Contactos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Empresas" asp-action="Index"><i class="fa fa-building-o"></i> Organizaciones</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/Contactos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Contactos" asp-action="Index"><i class="fa fa-users"></i> Todos los Contactos</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/Contactos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Clientes" asp-action="Index"><i class="fa fa-user"></i> Clientes</a>
            </li>

            <li class="treeview @(Html.IsMenuActive("/Contactos") ? "active" : "")">
                <a href="/Contactos">
                    <i class="fa fa-users"></i> <span>Definiciones</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="nav-item @(Html.IsMenuActive("/Contactos") ? "active" : "")">
                        <a class="nav-link text-dark" asp-controller="DocumentoTipos" asp-action="Index"><i class="fa fa-link"></i> Documento Tipos</a>
                    </li>

                    <li class="nav-item @(Html.IsMenuActive("/Contactos") ? "active" : "")">
                        <a class="nav-link text-dark" asp-controller="Documentos" asp-action="Index"><i class="fa fa-link"></i> Documentos</a>
                    </li>
                </ul>

            </li>
        </ul>
    </li>

    <li class="treeview @(Html.IsMenuActive("/Localidades") ? "active" : "")">
        <a href="/Paises">
            <i class="fa fa-globe"></i> <span>Localidades</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li class="nav-item @(Html.IsMenuActive("/Paises") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Paises" asp-action="Index"><i class="fa fa-map"></i> Paises</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/Provincias") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Provincias" asp-action="Index"><i class="fa fa-map-marker"></i> Provincias</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/Municipios") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Municipios" asp-action="Index"><i class="fa fa-map-marker"></i> Municipios</a>
            </li>
            <li class="nav-item @(Html.IsMenuActive("/Distritos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Distritos" asp-action="Index"><i class="fa fa-map-marker"></i> Distritos</a>
            </li>
            <li class="nav-item @(Html.IsMenuActive("/Sectores") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="Sectores" asp-action="Index"><i class="fa fa-map-marker"></i> Sectores</a>
            </li>
        </ul>
    </li>

    <li class="treeview @(Html.IsMenuActive("/InventarioAlmacenes") ? "active" : "")">
        <a href="/Paises">
            <i class="fa fa-cubes"></i> <span>Inventarios</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>

        <ul class="treeview-menu">
            <li class="nav-item @(Html.IsMenuActive("/InventarioAlmacenes") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="InventarioAlmacenes" asp-action="Index"><i class="fa fa-cube"></i> Almacenes</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/InventarioArticulos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="InventarioArticulos" asp-action="Index"><i class="fa fa-tags"></i> Artículos</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/InventarioArticulos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="InventarioArticulos" asp-action="Index"><i class="fa fa-tags"></i> Clases</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/InventarioArticulos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="InventarioArticulos" asp-action="Index"><i class="fa fa-tags"></i> Tipos</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/InventarioArticulos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="InventarioArticulos" asp-action="Index"><i class="fa fa-tags"></i> Categorias</a>
            </li>


            <li class="nav-item @(Html.IsMenuActive("/InventarioArticulos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="InventarioArticulos" asp-action="Index"><i class="fa fa-tags"></i> Marcas</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/InventarioArticulos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="InventarioArticulos" asp-action="Index"><i class="fa fa-tags"></i> Modelos</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/InventarioArticulos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="InventarioArticulos" asp-action="Index"><i class="fa fa-tags"></i> Unidades</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/InventarioArticulos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="InventarioArticulos" asp-action="Index"><i class="fa fa-tags"></i> Ubicaciones</a>
            </li>


        </ul>
    </li>

    <li class="treeview @(Html.IsMenuActive("/Seguridad") ? "active" : "")">
        <a href="/Seguridad">
            <i class="fa fa-cubes"></i> <span>Seguridad</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>

        <ul class="treeview-menu">
            <li class="nav-item @(Html.IsMenuActive("/SeguridadGrupos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="SeguridadGrupos" asp-action="Index"><i class="fa fa-tags"></i> Grupos</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/SeguridadTipos") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="SeguridadTipos" asp-action="Index"><i class="fa fa-tags"></i> Tipos</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/SeguridadOpciones") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="SeguridadOpciones" asp-action="Index"><i class="fa fa-tags"></i> Opciones</a>
            </li>

            <li class="nav-item @(Html.IsMenuActive("/SeguridadFormularios") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="SeguridadFormularios" asp-action="Index"><i class="fa fa-tags"></i> Formularios</a>
            </li>


            <li class="nav-item @(Html.IsMenuActive("/SeguridadUsuarios") ? "active" : "")">
                <a class="nav-link text-dark" asp-controller="SeguridadUsuarios" asp-action="Index"><i class="fa fa-tags"></i> Usuarios</a>
            </li>
        </ul>
    </li>
</ul>